### ISSUE TITLE
Invoke does not return promise

### ISSUE THREAD

**Issue by ivarnm** [quangdaon/vue-signalr#1]
How are we meant to get the data that resolves with the server method on invoke?

![image](https://user-images.githubusercontent.com/36505347/123924432-40c07100-d98a-11eb-88ac-ff65fc376d2f.png)

![image](https://user-images.githubusercontent.com/36505347/123924562-6188c680-d98a-11eb-8cc5-225d7b1f93d3.png)

**Comment by quangdaon** [comment]
Hi @ivarnm! Thanks for the feedback. Tbh, I didn't even realize you could listen to an invoke call 😅 Unfortunately, I'm on vacation and won't have access to my computer for a couple weeks, but anyone is welcome to submit a PR to fix this before then.

In the meantime, if you have access to the server, I'd recommend sending a separate event and listening to it with `on`.
