### ISSUE TITLE
Expose connection object through service

### ISSUE THREAD

**Issue by quangdaon** [quangdaon/vue-signalr#20]
Add a method to get the SignalR connection object so users can access features not inherently supported by the plugin. I envision this being something like:

```
const signalr = useSignalR();
const connection = signalr.getConnection(); // Returns signalr.connection
```

**Comment by IGx89** [comment]
FYI you could make use of TypeScript getters here too:
'''
get connection(): HubConnection {
    return this._connection;
}

const connection = signalr.connection; // Returns signalr.connection
'''

That's how the SignalR client itself exposes variables: https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/ts/signalr/src/HubConnection.ts#L136
