### ISSUE TITLE
Better support for reconnections

### ISSUE THREAD

**Issue by quangdaon** [quangdaon/vue-signalr#22]
The service was originally designed to just manage the first connection and then assumes everything is sailing smoothly, but of course that isn't always the case. I added support for automatic reconnect with #9 but did not update the service to acknowledge that.

One issue that will help with this is #19.

Other ideas:
- Rename the private `connected` flag to `initiated` as this will only be used once the initial connection is established
- Create a new `connected` flag - this will be tracked similar to the alternate case in #19. It should be a private Ref with a `getConnectionStatus` method to expose it.

**Comment by IGx89** [comment]
Would be very handy if `connected` could be reactive as well (`Ref<boolean>`). That's how vue-router exposes the [currentRoute property](https://next.router.vuejs.org/api/#currentroute), for example.

**Comment by quangdaon** [comment]
Yep, that's what I was going for, but forgot to include it!
