### ISSUE TITLE
Provide composable for easier use

### ISSUE THREAD

**Issue by IlCallo** [quangdaon/vue-signalr#4]
It's pretty common to provide features via "composable" functions in Vue3.
A super-simple implementation would be something like

```ts
export function useSignalR() {
  const signalr = inject(SignalRSymbol);

  if (!signalr) {
    throw new Error('Failed to inject SignalR');
  }

  // Other code could possibly be executed here

  return signalr;
}
```

This would at least avoid the user to add injection runtime check every time

**Comment by quangdaon** [comment]
Hi, thanks for the feedback! I'm actually just transitioning from Vue 2 to 3, so I didn't know about this pattern. Reopening as it's something I'd like to add to this package.
